module.exports = function (sequelize, DataTypes) {

    const Cci = sequelize.define("Cci", {
        auditId: { type: DataTypes.INTEGER, allowNull: false },
        a1: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a2: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a3: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a4: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a5: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a6: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a7: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a8: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a9: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a10: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a11: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a12: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a13: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a14: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a15: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a16: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a17: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a18: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a19: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a20: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a21: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a22: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a23: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a24: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a25: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a26: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a27: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a28: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a29: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a30: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a31: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a32: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a33: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a34: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a35: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a36: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a37: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a38: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a39: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a40: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a41: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a42: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a43: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a44: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a45: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a46: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a47: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a48: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a49: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a50: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a51: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a52: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a53: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a54: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a55: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a56: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a57: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a58: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a59: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a60: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a61: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a62: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a63: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a64: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a65: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a66: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a67: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a68: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a69: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a70: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a71: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a72: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a73: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a74: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a75: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a76: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a77: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a78: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a79: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a80: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a81: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a82: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a83: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a84: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a85: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a86: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a87: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a88: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a89: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a90: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a91: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a92: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a93: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a94: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a95: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a96: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a97: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a98: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a99: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a100: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a101: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a102: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a103: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a104: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a105: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a106: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a107: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a108: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a109: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a110: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a111: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a112: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a113: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a114: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a115: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a116: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a117: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a118: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a119: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a120: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a121: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a122: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a123: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a124: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        a125: { type: DataTypes.TEXT, allowNull: true, defaultValue: "" },
        createdAt: {
            type: DataTypes.DATE,
            allowNull: true
        },
        updatedAt: {
            type: DataTypes.DATE,
            allowNull: true
        }
    }, {
            tableName: "cci"
        });

    return Cci;
};
